### ISSUE TITLE
rajouter les zones d'occupation en orange

### ISSUE THREAD

**Issue by alexandrecuer** [emmademareywilliams/stage#19]
Il faudrait faire une branche permettant de visualiser les zones d'occupation sur le graphique qui rejoue un épisode, comme on visualise déjà la zone de confort en vert.

Pour cela, s'inspirer de 

https://github.com/alexjunk/BIOS/blob/564e12dd00b73e6546f371ccef6cb71ac0cfd3e8/RLTrainingBox.py#L815

Il faudrait mettre cela ds la classe Environnement, ds la méthode xr a laquelle on pourrait au passage donner un autre nom.

Pour proposer cette modification et maintenant que tu a compris comment manipuler les branches : 
- créer une nouvelle branche a partir de alex_branch
- faire les modifs ds cette nouvelle branche
- une fois ts les tests faits, merger cette nvlle fonctionnalité ds alex_branch

**Comment by emmademareywilliams** [comment]
Après modification de `RLToolbox.py`, on obtient la visualisation des périodes d'occupation comme avant : 

![periodes_occupation](https://user-images.githubusercontent.com/85568176/133437457-1daaabcd-9d5f-4444-a457-6417727cadcb.png)

Modifications apportées : 

https://github.com/emmademareywilliams/stage/blob/1b6bab41b4ec9596282dfc22c14891267387af36/Neurones/RLtoolbox.py#L163

**Comment by alexandrecuer** [comment]
parfait, tu peux tout merger dans alex_branch et dans reorganise stp :-)

**Comment by emmademareywilliams** [comment]
Fait :+1:
