### ISSUE TITLE
Modification du comportement modèle 

### ISSUE THREAD

**Issue by emmademareywilliams** [emmademareywilliams/stage#22]
En modifiant la fonction `EnvHystNocc` comme on a dit :

https://github.com/emmademareywilliams/stage/blob/86f659e9d178bfd4a7becc438f3ff9cda47073c5/Neurones/play.py#L79

et ici:

https://github.com/emmademareywilliams/stage/blob/86f659e9d178bfd4a7becc438f3ff9cda47073c5/Neurones/play.py#L73

On obtient le bon comportement pour le modèle au timestamp qui posait problème (1610404340) : 

![comportement_modele_ok](https://user-images.githubusercontent.com/85568176/133618802-99110f38-f530-4713-95ae-1ee39511f3fc.png)

**Comment by emmademareywilliams** [comment]
J'ai fait joué le réseau de ce matin (réentraîné sur 400 épisodes avec la fonction reward "vote du public") et au niveau des stats c'est également beaucoup mieux : 

(R, C) | Nb points inconfort agent | Nb points inconfort modèle 
--|--|--
(3.08e-4, 8,63e8) | 1.4 | 1 
(5e-4, 2e9) | 1.9 | 1.9 
(1e-3, 2e9) | 1.8 | 1.8

(Sachant que cet agent-ci a un comportement globalement hystérésis)

**Comment by alexandrecuer** [comment]
pour l'hysteresys en mode occupation, il faut laisser tel quel je pense : 
```
if datas[i-1,2] > self._Tc + self._hh or datas[i-1,2] < self._Tc - self._hh :
    action = datas[i-1,2] <= self._Tc
    datas[i,0] = action * self._max_power
```
quant on est hors de la fenêtre d'hystéresys, on arrête de chauffer si on est en dessus, ou on chauffe quand on est au dessus 

ce que tu fais, c'est un hystéresys avec hh = 0

OK pour la partie 2 par contre

**Comment by emmademareywilliams** [comment]
En effet, avec cette modif le modèle "parcourt" toute la zone de confort : 

![comportement_modele_bis](https://user-images.githubusercontent.com/85568176/133632298-c905e27d-3d97-44dc-94e8-0a959b1c2c21.png)

Sur toutes les stats que j'ai fait tourner avec le nouveau code, on a entre 1 et 2 heures d'inconfort max pour le modèle, ça va beaucoup mieux !
