### ISSUE TITLE
bug du récepteur RS232

### ISSUE THREAD

**Issue by alexandrecuer** [emmademareywilliams/stage#8]

**Comment by alexandrecuer** [comment]
plus aucun paquet capté par la socket depuis 06.00 du matin
probablement récepteur RS232 qui est en rideau électriquement.
Voir combien de temps celà dure
Si celà persiste, probablement arrêter le PI depuis l'interface admin, couper le courant en abaissant le disjoncteur et remettre en service

**Comment by alexandrecuer** [comment]
Hello
Jai vu que tu avais rebooté mais ça n'a pas remis en route la lecture des paquets
Est ce que tu as as bien coupé électriquement au disjoncteur ? Est ce que l'antenne qui est sur la chaise s'est cassée la figure :-) ?

**Comment by alexandrecuer** [comment]
A mon avis ce n'est pas un pb de code mais de matériel.

**Comment by emmademareywilliams** [comment]
L'antenne est toujours bien en place ! 
J'ai shutdown le PI, puis coupé au disjoncteur, puis rallumé et enfin rebooté le PI
La LED verte du PI clignote maintenant, mais toujours pas de paquets reçus

**Comment by alexandrecuer** [comment]
Ok il y a bien une led orange allumée sur le récepteur ?

**Comment by emmademareywilliams** [comment]
Les 6 LED du récepteur s'allument tour à tour 
D'abord la LED rouge / orange qui donne sur l'extérieur du boîtier, puis les 5 autres, toujours dans le même ordre

**Comment by alexandrecuer** [comment]
Peut-être n'as tu pas assez attendu avant de remettre le courant sur Themus :
```
2021-07-05 09:36:46,506    DEBUG - signal de fermeture reçu
2021-07-05 09:36:49,134  WARNING - timed out
2021-07-05 09:36:49,235    DEBUG - fermeture
2021-07-05 09:37:19,980    DEBUG - ........OUVERTURE DU FIELD MANAGER........
2021-07-05 09:37:24,991  WARNING - timed out
```
Fermeture à 9::36 et réouverture à 9:37 
Normalement qt on coupe le jus, ça prend quelques minutes entre l'arrêt et le redémarrage

**Comment by emmademareywilliams** [comment]
Ok, je réessaie de couper le courant

**Comment by alexandrecuer** [comment]
Pour les leds sur le récepteur, ce n'est pas du tt normal....elles doivent clignoter tour à tour mais une seule fois puis une seule reste allumée en orange persistant

**Comment by alexandrecuer** [comment]
Il faut que tu laisses themis éteinte pendant 30 ou 60 secondes

**Comment by emmademareywilliams** [comment]
J'ai laissé le système éteint pendant 2/3 minutes, puis je l'ai redémarré et j'ai rebooté le PI 
Les leds du récepteurs s'allument toujours de la même façon

**Comment by alexandrecuer** [comment]
Ok il y a donc un pb :-) 
Je ne sais pas trop ce que c'est 
Tu peux prendre une petite photo ou vidéo des les et la poster ici ds un message ?
Je vais faire un mel au support technique.

**Comment by emmademareywilliams** [comment]
[https://drive.google.com/file/d/1tU80YpCaNhqUYwRXBlwC5luqak-VUXoZ/view?usp=sharing](Lien vers la vidéo)
Je n'ai rien trouvé encore dans la doc technique sur ce problème, je vais continuer à chercher

**Comment by emmademareywilliams** [comment]
[Lien vers la vidéo](https://drive.google.com/file/d/1tU80YpCaNhqUYwRXBlwC5luqak-VUXoZ/view?usp=sharing)
Ça ira mieux comme ça :)

**Comment by alexandrecuer** [comment]
Pas de chance avec ces récepteurs RS232.

Je viens d'écrire au support technique, on verra bien leur retour

Je pense que tu ne trouveras rien dans la doc. Ces pbs de matériels sont assez compliqués à cerner. On avisera à mon retour :-) 

Penches toi plutôt sur emoncms, la création d'un flux pour décrire le fonctionnement de la pompe et voir si tu arrives à fitter un modèle RC sur les données du collège Marc Bloch. Une fois ton flux pompe calé, prends une valeur de débit fixe, du style 1 à 2 m3/h...

Have a nice week

Alexandre

**Comment by emmademareywilliams** [comment]
En effet, la doc n'a pas été d'une grande aide... Je suis repartie sur la création du flux de la pompe. 
Bonne semaine également et bonnes vacances !

**Comment by alexandrecuer** [comment]
Je viens de voir ta vidéo

Normalement les switches doivent être ainsi positionnés pour que le matériel fonctionne en mode transparent :

    DIP1 : 1,2 ON 3,4,5,6 OFF
    DIP2 : 1,2,3 OFF

pour le DIP 1 c'est OK il me semble
pour le DIP 2 ce n'est pas OK, on dirait qu'on a 2 sur ON, faudrait qu'il soit sur OFF

Pour changer les DIP, prendre un trombone. il doit y en avoir un derrière dans mon placard :-) le changement doit se faire avec tout e système éteint

**Comment by emmademareywilliams** [comment]
C'est moi qui avait changé le switch tout à l'heure, de manière à ce qu'il corresponde à ce qu'il y a dans la doc constructeur
Bien entendu ça n'a pas marché, et j'ai oublié de le remettre dans sa position initiale...

**Comment by alexandrecuer** [comment]
OK mais dans ce cas, est-ce que les 5 LED continuent de clignoter avec le switch 2 du DIP2 à OFF ?
ou est-ce que tu as seulement la LED numéro 5 allumée en orange ?

**Comment by emmademareywilliams** [comment]
C'est toujours la même chose (les 5 leds clignotent), que le switch soit sur ON ou sur OFF

**Comment by alexandrecuer** [comment]
OK il serait qd même bien de couper ce récepteur. 

Je te proposes donc d'éteindre Themis. Pour ne rien avoir à débrancher au niveau du bloc d'alim, tu prends l'alimentation 12V du routeur que je t'avais passée semaine dernière et que j'ai rangée dans le placard de mon bureau, celui le plus près de la porte.....normalement c'est dans un carton, sur la seconde étagère en partant du haut, c'est une alim 12V avec un connecteur blanc...il ne doit y en avoir qu'une

une fois Themis éteinte, tu débranches le connecteur power du routeur (connecteur blanc) et tu connectes à la place l'alim trouvée dans mon placard.....tu n'as même pas à éteindre le rapsberry mais comme celà, le récepteur sera éteint.....

**Comment by emmademareywilliams** [comment]
C'est fait !
